#!/usr/bin/env bash

source ./.bashrc

# https://docs.docker.com/config/containers/multi-service_container/
# turn on bash's job control
set -m

./docker/server/pocket-ic/serve &

./docker/server/pocket-ic/config

./docker/server/cli/wait

./docker/server/cli/deploy

./docker/server/console/start &

./docker/server/cli/start

# now we bring the primary process back into the foreground
# and leave it there
fg %1

# TODO: this is probably not called yet
./docker/server/pocket-ic/clean-up