#!/usr/bin/env bash

./docker/server/wait-port "$REPLICA_PORT"

SUBNET_CONFIG="{\"state_config\": \"New\", \"instruction_config\": \"Production\", \"dts_flag\": \"Enabled\"}"

# https://github.com/dfinity/ic/blob/master/packages/pocket-ic/src/common/rest.rs#L557
ICP_CONFIG="{\"beta_features\": \"Disabled\", \"canister_backtrace\": \"Enabled\", \"function_name_length_limits\": \"Enabled\", \"canister_execution_rate_limiting\": \"Enabled\"}"

curl -s -S -X POST -H "Content-Type: application/json" "http://localhost:$REPLICA_PORT/instances" -d "{\"subnet_config_set\": {\"nns\": ${SUBNET_CONFIG}, \"sns\": ${SUBNET_CONFIG}, \"ii\": ${SUBNET_CONFIG}, \"fiduciary\": null, \"bitcoin\": null, \"system\": [], \"application\": [${SUBNET_CONFIG}], \"verified_application\": []}, \"state_dir\": \"${STATE_REPLICA_DIR}\", \"icp_config\": ${ICP_CONFIG}}" > /dev/null

curl -s -S -X POST -H "Content-Type: application/json" "http://localhost:$REPLICA_PORT/instances/0/auto_progress" -d '{"artificial_delay_ms": null}' > /dev/null

curl -s -S -X POST -H 'Content-Type: application/json' "http://localhost:$REPLICA_PORT/http_gateway" -d "{\"forward_to\": {\"Replica\": \"http://localhost:$REPLICA_PORT/instances/0/\"}, \"port\": $PORT, \"ip_addr\": \"0.0.0.0\"}" > /dev/null