#!/usr/bin/env bash

./docker/server/wait-port "$REPLICA_PORT"

SUBNET_CONFIG="{\"state_config\": \"New\", \"instruction_config\": \"Production\", \"dts_flag\": \"Enabled\"}"

# https://github.com/dfinity/ic/blob/master/packages/pocket-ic/src/common/rest.rs#L557
ICP_CONFIG="{\"beta_features\": \"Disabled\", \"canister_backtrace\": \"Enabled\", \"function_name_length_limits\": \"Enabled\", \"canister_execution_rate_limiting\": \"Enabled\"}"

# We need the set up the HTTP gateway in the same call so that the NNS dapp can be configured with the right gateway URL
# https://github.com/dfinity/ic/blob/master/packages/pocket-ic/src/common/rest.rs#L603
INSTANCE_HTTP_GATEWAY="{
  \"ip_addr\": \"0.0.0.0\",
  \"port\": ${PORT},
  \"domains\": null,
  \"https_config\": null
}"

# Configures the instance to make progress automatically
# https://github.com/dfinity/ic/blob/master/packages/pocket-ic/src/common/rest.rs#L637
INITIAL_TIME="{\"AutoProgress\": {\"artificial_delay_ms\": null}}"

curl -s -S -X POST -H "Content-Type: application/json" "http://localhost:$REPLICA_PORT/instances" -d "{\"subnet_config_set\": {\"nns\": ${SUBNET_CONFIG}, \"sns\": ${SUBNET_CONFIG}, \"ii\": ${SUBNET_CONFIG}, \"fiduciary\": null, \"bitcoin\": null, \"system\": [], \"application\": [${SUBNET_CONFIG}], \"verified_application\": []}, \"state_dir\": \"${STATE_REPLICA_DIR}\", \"icp_config\": ${ICP_CONFIG}, \"initial_time\": ${INITIAL_TIME}, \"icp_features\": ${NETWORK_SERVICES}, \"http_gateway_config\": ${INSTANCE_HTTP_GATEWAY}}" > /dev/null
