#!/usr/bin/env bash

if [ -z "${NETWORK_SERVICES:-}" ]; then
  if [ "$CLI_BUILD" = "satellite" ]; then
    NETWORK_SERVICES='{
      "registry": false,
      "cmc": false,
      "icp": true,
      "cycles": false,
      "nns": false,
      "sns": false,
      "ii": true,
      "nnsDapp": false
    }'
  else
    NETWORK_SERVICES='{
      "registry": false,
      "cmc": true,
      "icp": true,
      "cycles": true,
      "nns": true,
      "sns": false,
      "ii": true,
      "nnsDapp": false
    }'
  fi
fi

# https://github.com/dfinity/ic/blob/master/packages/pocket-ic/src/common/rest.rs#L583
ICP_FEATURES=$(echo "$NETWORK_SERVICES" | jq '{
  registry:       (if .registry == true then "DefaultConfig" else null end),
  cycles_minting: (if .cmc == true then "DefaultConfig" else null end),
  icp_token:      (if .icp == true then "DefaultConfig" else null end),
  cycles_token:   (if .cycles == true then "DefaultConfig" else null end),
  nns_governance: (if .nns == true then "DefaultConfig" else null end),
  sns:            (if .sns == true then "DefaultConfig" else null end),
  ii:             (if .ii == true then "DefaultConfig" else null end),
  nns_ui:         (if .nnsDapp == true then "DefaultConfig" else null end)
}')

export ICP_FEATURES

