#!/usr/bin/env bash

"$TARGET_DIR/ic-starter" --replica-path "$TARGET_DIR/replica" \
                    --http-port "$REPLICA_PORT" \
                    --state-dir "$STATE_REPLICA_DIR" \
                    --create-funds-whitelist '*' \
                    --subnet-type application \
                    --chain-key-ids ecdsa:Secp256k1:juno_test_key \
                    --chain-key-ids schnorr:Bip340Secp256k1:juno_test_key \
                    --log-level error \
                    --use-specified-ids-allocation-range \
                    --consensus-pool-backend lmdb \
                    --subnet-features canister_sandboxing \
                    --subnet-features http_requests \
                    --initial-notary-delay-millis 600 \
                    --metrics-addr=[100::]:0 \
                    --canister-http-uds-path /juno/.juno/sock