#!/usr/bin/env bash

source ./.bashrc

JUNO_REPO="$JUNO_MAIN_DIR"

if [ "$CLI_BUILD" == "skylab" ]; then
  # npm error signal SIGILL esbuild because package-lock contains a reference to esbuild arm
  rm "${JUNO_REPO}"/package-lock.json

  # .svelte-kit/tsconfig.json not found - npm run prepare is not run because ignore-scripts=true is defined
  # that's why we run a custom install script that do npm i && npm run prepare
  npm --prefix "${JUNO_REPO}" run bootstrap:install

  # we use npm run preview to run the console that's why we need to build the application
  npm --prefix "${JUNO_REPO}" run build:skylab
fi