#!/usr/bin/env bash

source ./.bashrc

JUNO_REPO="$JUNO_MAIN_DIR"

if [ "$CLI_BUILD" == "skylab" ]; then
  npm --prefix "${JUNO_REPO}" run --silent preview -- --port "$CONSOLE_PORT" --host &

  if ./docker/server/wait-port "$CONSOLE_PORT"; then
    echo "🖥️   Console started on port ${CONSOLE_PORT}"
  fi
fi