#!/usr/bin/env bash

./docker/wait-port "$REPLICA_PORT"

SUBNET_CONFIG="{\"state_config\": \"New\", \"instruction_config\": \"Production\", \"dts_flag\": \"Enabled\"}"

curl -X POST -H "Content-Type: application/json" http://localhost:8000/instances -d "{\"subnet_config_set\": {\"nns\": ${SUBNET_CONFIG}, \"sns\": ${SUBNET_CONFIG}, \"ii\": ${SUBNET_CONFIG}, \"fiduciary\": null, \"bitcoin\": null, \"system\": [], \"application\": [${SUBNET_CONFIG}], \"verified_application\": []}, \"state_dir\": null, \"nonmainnet_features\": false}"

curl -X POST -H "Content-Type: application/json" http://localhost:8000/instances/0/update/set_time -d "{\"nanos_since_epoch\": $(date +%s%N)}"

curl -X POST -H "Content-Type: application/json" http://localhost:8000/instances/0/auto_progress -d '{"artificial_delay_ms": null}'

curl -X POST -H 'Content-Type: application/json' http://localhost:8000/http_gateway -d '{"forward_to": {"Replica": "http://localhost:8000/instances/0/"}, "port": 5987, "ip_addr": "0.0.0.0"}'
