#!/usr/bin/env bash

set -euo pipefail

METADATA_IC=./ic.json
METADATA_MODULES=./ic.json

DIR=target

if [ ! -d "$DIR" ]; then
  mkdir "$DIR"
fi

function download_ic() {
    local component=$1

    download "$component" "$METADATA_IC" true
}

function download_module() {
    local component=$1

    download "$component" "$METADATA_MODULES" false
}

function download() {
    local component=$1
    local metadata=$2
    local unpkg=$3

    local url=($(jq -r ".\"${component}\".url" ${metadata}))
    local commit=($(jq -r ".\"${component}\".commit" ${metadata}))

    local download_url=${url/"{commit}"/$commit}

    echo "Downloading $component from $download_url"
    curl -L -o "$DIR/$component.gz" "$download_url"

    if "${unpkg}"; then
        echo "Unpacking $DIR/$component.gz"
        gunzip "$DIR/$component.gz"
    fi
}

download_ic "replica"
download_ic "ic-starter"
download_ic "canister_sandbox"
download_ic "sandbox_launcher"
download_ic "icx-proxy"

download_module "internet_identity"