#!/usr/bin/env bash

set -euo pipefail

METADATA=./ic.json

DIR=target

if [ ! -d "$DIR" ]; then
  mkdir "$DIR"
fi

function download_unpack() {
    local component=$1

    download "$component" true
}

function download() {
    local component=$1
    local unpkg=$2
    local url=($(jq -r ".\"${component}\".url" $METADATA))
    local commit=($(jq -r ".\"${component}\".commit" $METADATA))

    local download_url=${url/"{commit}"/$commit}

    echo "Downloading $component from $download_url"
    curl -L -o "$DIR/$component.gz" "$download_url"

    if "${unpkg}"; then
        echo "Unpacking $DIR/$component.gz"
        gunzip "$DIR/$component.gz"
    fi
}

download_unpack "replica"
download_unpack "ic-starter"
download_unpack "canister_sandbox"
download_unpack "sandbox_launcher"
download_unpack "icx-proxy"

download "internet_identity" false