#!/usr/bin/env bash

./target/ic-starter --replica-path ./target/replica \
                    --http-port "$REPLICA_PORT" \
                    --state-dir "$STATE_REPLICA_DIR" \
                    --create-funds-whitelist '*' \
                    --subnet-type application \
                    --ecdsa-keyid Secp256k1:juno_test_key \
                    --log-level info \
                    --use-specified-ids-allocation-range \
                    --consensus-pool-backend lmdb \
                    --subnet-features canister_sandboxing