#!/usr/bin/env bash

./target/ic-starter --replica-path ./target/replica \
                    --http-port "$REPLICA_PORT" \
                    --state-dir "$STATE_REPLICA_DIR" \
                    --create-funds-whitelist '*' \
                    --subnet-type application \
                    --chain-key-ids ecdsa:Secp256k1:juno_test_key \
                    --chain-key-ids schnorr:Bip340Secp256k1:juno_test_key \
                    --log-level warning \
                    --use-specified-ids-allocation-range \
                    --consensus-pool-backend lmdb \
                    --subnet-features canister_sandboxing \
                    --subnet-features http_requests \
                    --initial-notary-delay-millis 600 \
                    --canister-http-uds-path /juno/.juno/sock