#!/usr/bin/env bash

REPLICA_PORT=8000

./docker/replica $REPLICA_PORT &

./docker/wait-port $REPLICA_PORT

./docker/icx-proxy $REPLICA_PORT &

./docker/wait-port "$PORT"

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?