#!/usr/bin/env bash

./docker/wait-port "$PORT"

node ./cli/dist/index.js deploy --port "$PORT" --state "$STATE_CLI_DIR/modules.json"

node ./cli/dist/index.js config --port "$PORT" --state "$STATE_CLI_DIR/modules.json"
