#!/usr/bin/env bash

source ./.bashrc

npm --prefix cli ci

case "$CLI_BUILD" in
  console)
    npm --prefix cli run build:console
    ;;
  skylab)
    npm --prefix cli run build:skylab
    ;;
  *)
    npm --prefix cli run build:satellite
    ;;
esac