#!/usr/bin/env bash

node ./cli/dist/index.js deploy --port "$PORT" --state "$STATE_CLI_DIR/modules.json"

node ./cli/dist/index.js start --port "$PORT" --state "$STATE_CLI_DIR/modules.json"

node ./cli/dist/index.js watch --port "$PORT" --state "$STATE_CLI_DIR/modules.json" &

node ./cli/dist/index.js admin --port "$PORT" --state "$STATE_CLI_DIR/modules.json" --admin-port "$ADMIN_PORT"