name: Build and push Docker image
description: Build and push image for a single platform

inputs:
  image_name:
    required: true
  cli_build:
    required: true
  platform:
    required: true
  tag_suffix:
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ matrix.image_name }}
        tags: |
          type=semver,pattern={{major}}
          type=semver,pattern={{version}}
          type=raw,value=latest

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: ${{ inputs.platform }}
        tags: ${{ steps.meta.outputs.tags }}-${{ inputs.tag_suffix }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: CLI_BUILD=${{ inputs.cli_build }}
