services:
  juno-satellite:
    image: junobuild/satellite:latest
    ports:
      - 5987:5987
    volumes:
      - my_dapp:/juno/.juno
      - ./juno.dev.json:/juno/juno.dev.json

volumes:
  my_dapp: