import {AccountIdentifier} from '@icp-sdk/canisters/ledger/icp';
import {IDL} from '@icp-sdk/core/candid';
import {MAIN_IDENTITY_KEY, MINTER_IDENTITY_KEY} from '../constants/constants';
import {init} from '../declarations/icp_ledger.idl';
import {Module} from '../services/modules/module.services';
import type {ModuleDescription, ModuleInstallParams} from '../types/module';

export const ICP_LEDGER_CANISTER_ID = 'ryjl3-tyaaa-aaaaa-aaaba-cai';

const ICP_LEDGER: ModuleDescription = {
  key: 'icp_ledger',
  name: 'ICP Ledger',
  canisterId: ICP_LEDGER_CANISTER_ID
};

class IcpLedgerModule extends Module {
  override async install(context: ModuleInstallParams): Promise<void> {
    const {
      identities: {
        [MINTER_IDENTITY_KEY]: minterIdentity,
        [MAIN_IDENTITY_KEY]: mainIdentity,
        ...otherIdentities
      },
      ...rest
    } = context;

    const minterAccountIdentifier = AccountIdentifier.fromPrincipal({
      principal: minterIdentity.getPrincipal()
    }).toHex();

    const ledgerAccountIdentifier = AccountIdentifier.fromPrincipal({
      principal: mainIdentity.getPrincipal()
    }).toHex();

    const initArgs = {
      send_whitelist: [],
      token_symbol: ['ICP'],
      transfer_fee: [{e8s: 10_000n}],
      minting_account: minterAccountIdentifier,
      maximum_number_of_accounts: [],
      accounts_overflow_trim_quantity: [],
      transaction_window: [],
      max_message_size_bytes: [],
      icrc1_minting_account: [],
      archive_options: [],
      initial_values: [[ledgerAccountIdentifier, {e8s: 100_000_000_000n}]],
      token_name: ['Internet Computer'],
      feature_flags: []
    };

    const upgradeArgs = [];

    // Type definitions generated by Candid are not clean enough.
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    const arg = IDL.encode(init({IDL}), [
      this.status(context) === 'deployed' ? {Upgrade: upgradeArgs} : {Init: initArgs}
    ]);

    await super.install({
      identities: {
        [MINTER_IDENTITY_KEY]: minterIdentity,
        [MAIN_IDENTITY_KEY]: mainIdentity,
        ...otherIdentities
      },
      ...rest,
      arg
    });
  }
}

export const icpLedger = new IcpLedgerModule(ICP_LEDGER);
