import {assertNonNullish} from '@dfinity/utils';
import {IDL} from '@icp-sdk/core/candid';
import {Principal} from '@icp-sdk/core/principal';
import {init} from '../declarations/icp_index.idl';
import {Module} from '../services/modules/module.services';
import type {ModuleDescription, ModuleInstallParams} from '../types/module';

const ICP_INDEX: ModuleDescription = {
  key: 'icp_index',
  name: 'ICP Index',
  canisterId: 'qhbym-qaaaa-aaaaa-aaafq-cai'
};

class IcpIndexModule extends Module {
  override async install({state, ...rest}: ModuleInstallParams): Promise<void> {
    const canisterId = state.getModule('icp_ledger')?.canisterId;

    assertNonNullish(
      canisterId,
      'Cannot configure ICP index because the ICP ledger id is unknown.'
    );

    // Type definitions generated by Candid are not clean enough.
     
    const arg = IDL.encode(init({IDL}), [{ledger_id: Principal.fromText(canisterId)}]);

    await super.install({
      state,
      arg,
      ...rest
    });
  }
}

export const icpIndex = new IcpIndexModule(ICP_INDEX);
