import {toNullable} from '@dfinity/utils';
import {IDL} from '@icp-sdk/core/candid';
import type {InternetIdentityInit} from '../declarations/internet_identity';
import {init} from '../declarations/internet_identity.idl';
import {Module} from '../services/modules/module.services';
import type {ModuleDescription, ModuleInstallParams} from '../types/module';

const INTERNET_IDENTITY: ModuleDescription = {
  key: 'internet_identity',
  name: 'Internet Identity',
  canisterId: 'rdmx6-jaaaa-aaaaa-aaadq-cai'
};

class InternetIdentityModule extends Module {
  override async install(params: ModuleInstallParams): Promise<void> {
    const initArgs: InternetIdentityInit = {
      archive_config: toNullable(),
      canister_creation_cycles_cost: toNullable(),
      assigned_user_number_range: toNullable(),
      register_rate_limit: toNullable(),
      captcha_config: toNullable({
        max_unsolved_captchas: 50n,
        captcha_trigger: {
          Static: {
            CaptchaDisabled: null
          }
        }
      }),
      fetch_root_key: [true],
      openid_google: [],
      is_production: [false],
      enable_dapps_explorer: [false],
      analytics_config: [],
      related_origins: []
    };

    // Type definitions generated by Candid are not clean enough.
     
    const arg = IDL.encode(init({IDL}), [[initArgs]]);

    await super.install({
      arg,
      ...params
    });
  }
}

export const internetIdentity = new InternetIdentityModule(INTERNET_IDENTITY);
