#!/usr/bin/env bash

set -euo pipefail

METADATA_IC=./ic.json
METADATA_MODULES=./modules.json

DIR="$TARGET_DIR"

if [ ! -d "$DIR" ]; then
  mkdir "$DIR"
fi

function download_ic() {
    readarray -t keys < <(jq -r 'keys[]' $METADATA_IC)
    for i in "${keys[@]}"; do
        download "$i" "$METADATA_IC" true
    done
}

function download_modules() {
    readarray -t keys < <(jq -r 'keys[]' $METADATA_MODULES)
    for i in "${keys[@]}"; do
        download "$i" "$METADATA_MODULES" false
    done
}

function download() {
    local key=$1
    local metadata=$2
    local unpkg=$3

    local url=($(jq -r ".\"${key}\".url" ${metadata}))
    local commit=($(jq -r ".\"${key}\".commit" ${metadata}))

    local download_url=${url/"{commit}"/$commit}

    echo "Downloading $key from $download_url"
    curl -L -o "$DIR/$key.gz" "$download_url"

    if "${unpkg}"; then
        echo "Unpacking $DIR/$key.gz"
        gunzip "$DIR/$key.gz"
    fi
}

download_ic
download_modules