#!/usr/bin/env bash

set -euo pipefail

DIR="$TARGET_DIR"

if [ ! -d "$DIR" ]; then
  mkdir "$DIR"
fi

# Use a specific commit (optional, or switch to refs/heads/main if needed)
COMMIT=a1d9b4cd252efc534d674e02e55856922cdb7bf6

curl -L -o "$DIR/juno.tar.gz" https://github.com/junobuild/juno/archive/$COMMIT.tar.gz

tar -xf "$DIR/juno.tar.gz" -C "$DIR"

# Rename the extracted folder to juno-main
mv "$DIR/juno-$COMMIT" "$JUNO_MAIN_DIR"

echo "juno source downloaded and extracted to $JUNO_MAIN_DIR."
