#!/usr/bin/env bash

source ./.bashrc

JUNO_REPO="/juno/target/juno-main"

if [ "$CLI_BUILD" == "satellite" ]; then
  # npm error signal SIGILL esbuild because package-lock contains a reference to esbuild arm
  rm ${JUNO_REPO}/package-lock.json
  npm --prefix ${JUNO_REPO} install
fi