#!/usr/bin/env bash

source ./.bashrc

JUNO_REPO="/juno/target/juno-main"

if [ "$CLI_BUILD" == "satellite" ]; then
  npm --prefix ${JUNO_REPO} run --silent dev:silent -- --port "$CONSOLE_PORT" &

  ./docker/wait-port "$CONSOLE_PORT"

  echo "🖥️  Console started on port ${CONSOLE_PORT}"
fi