#!/usr/bin/env bash

set -euo pipefail

DIR=target

if [ ! -d "$DIR" ]; then
  mkdir "$DIR"
fi

# Use a specific commit (optional, or switch to refs/heads/main if needed)
COMMIT=f16fab9b0d13a55dc0ab05dad8878c9d550b647d

curl -L -o "$DIR/juno.tar.gz" https://github.com/junobuild/juno/archive/$COMMIT.tar.gz

tar -xf "$DIR/juno.tar.gz" -C "$DIR"

# Rename the extracted folder to juno-main
mv "$DIR/juno-$COMMIT" "$DIR/juno-main"

echo "juno source downloaded and extracted to $DIR/juno-main."
