name: Build Docker Image

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build AMD64 Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile \
            --output type=docker \
            .

  build-arm64:
    runs-on: macos-15-xlarge
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARM64 Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --file Dockerfile \
            --output type=docker \
            .
