name: Build Docker Image

on:
  pull_request:
  workflow_dispatch:
    inputs:
      platform:
        description: "Target platform"
        required: false
        default: "linux/amd64"
        type: choice
        options:
          - linux/amd64
          - linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set platform
        id: platform
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "PLATFORM=${{ github.event.inputs.platform }}" >> $GITHUB_OUTPUT
          else
            echo "PLATFORM=linux/amd64" >> $GITHUB_OUTPUT
          fi

      - name: Build the Docker image
        run: |
          docker buildx build \
            --platform ${{ steps.platform.outputs.PLATFORM }} \
            --file Dockerfile \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .
