name: Build Docker Images

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Base Docker Image
        run: docker build -t junobuild/base -f Dockerfile.base .

      - name: Cache Base Image
        run: docker save junobuild/base | gzip > juno-base.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: juno-base
          path: juno-base.tar.gz

  build-main:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cached Base Image
        uses: actions/download-artifact@v4
        with:
          name: juno-base

      - name: Load Base Image
        run: docker load < juno-base.tar.gz

      - name: Build Main Docker Image
        run: docker build -t junobuild/satellite -f Dockerfile .
