name: Checks

on:
  pull_request:
    paths:
      - 'cli/**'

defaults:
  run:
    working-directory: ./cli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build
        run: npm run build

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run lint

  may-merge:
    needs: ['format', 'lint', 'build']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
