name: CLI Checks

on:
  pull_request:
    paths:
      - 'cli/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build
        run: npm run build
        working-directory: ./cli

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run format:check
        working-directory: ./cli

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run lint
        working-directory: ./cli

  may-merge:
    needs: ['format', 'lint', 'build']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
