name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_base:
    name: Push Base Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: junobuild/base
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{version}}

      - name: Build and push Base Image (`junobuild/base`)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile.base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_main:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: push_base
    strategy:
      matrix:
        include:
          - image_name: junobuild/satellite
            cli_build: satellite
          - image_name: junobuild/console
            cli_build: console
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image_name }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{version}}

      - name: Build and push Docker image for ${{ matrix.image_name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: CLI_BUILD=${{ matrix.cli_build }}